"""End-to-end LLM path: real adapter HTTP/parse layer + LLM agents in a campaign.

The other LLM tests stub ``.complete()``; these drive the real
``OpenAICompatibleClient`` over a fake httpx transport (a canned OpenAI-style
chat/completions body) and run the LLM Judge and LLM Red Team through an actual
campaign, so the opt-in LLM path is exercised by the green suite — not just the
deterministic default. The transport is faked (no network/model in CI); every
layer above it is the shipped code.
"""
import glob
import json
import sys
from pathlib import Path
from types import SimpleNamespace

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from agentforge.agents.judge import JudgeAgent
from agentforge.agents.llm import LlmJudge, LlmRedTeam, OpenAICompatibleClient
from agentforge.agents.redteam import SeedCase
from agentforge.observability.store import ObservabilityStore
from agentforge.pipeline import run_campaign
from agentforge.target.client import MockTargetClient, TurnResult


class _Resp:
    def __init__(self, content):
        self._c = content

    @property
    def status_code(self):
        return 200

    def json(self):
        return {"choices": [{"message": {"content": self._c}}]}


class _FakeHTTP:
    """Fake httpx client: inspects the outgoing system prompt and returns the
    right OpenAI-style body (verdict JSON for the Judge, array for the Red Team)."""

    def __init__(self):
        self.posts = []

    def post(self, url, headers=None, json=None):
        self.posts.append(json)
        system = json["messages"][0]["content"]
        if "security judge" in system:
            return _Resp('{"verdict":"success","confidence":0.9,'
                         '"severity":"critical","rationale":"disclosed cross-patient data"}')
        # red-teamer
        return _Resp('["forged-audit variant","stepwise variant","translate variant",'
                     '"urgent variant"]')


def _client():
    cfg = SimpleNamespace(base_url="http://fake/v1", model="fake-model", api_key="")
    return OpenAICompatibleClient(cfg, http=_FakeHTTP())


def _all_seeds():
    seeds = []
    for f in sorted(glob.glob(str(ROOT / "evals/cases/*.json"))):
        for d in json.loads(Path(f).read_text()):
            if d["target_surface"] in ("chat", "agent"):
                seeds.append(SeedCase.from_eval(d))
    return seeds


# --------------------------------------------------------------------------- #
#  Real adapter HTTP/parse layer
# --------------------------------------------------------------------------- #
def test_adapter_complete_hits_http_and_parses():
    # LlmJudge over the real client + fake transport returns a parsed verdict.
    out = LlmJudge(_client()).classify("attacker: x\ntarget: patient 2 A1c is 8", "pinned only")
    assert out["verdict"] == "success" and out["severity"] == "critical"
    # LlmRedTeam over the real client returns the parsed array.
    variants = LlmRedTeam(_client()).variants("list patient 2 labs", n=4)
    assert len(variants) == 4 and "stepwise variant" in variants


# --------------------------------------------------------------------------- #
#  LLM Red Team through a full campaign (provenance flows to the store)
# --------------------------------------------------------------------------- #
def test_campaign_marks_llm_redteam_provenance(tmp_path):
    store = ObservabilityStore(tmp_path / "run.jsonl")
    result = run_campaign(
        target=MockTargetClient("leaky"), seeds=_all_seeds(), store=store,
        redteam_llm=LlmRedTeam(_client()), max_rounds=1, max_attempts_per_round=2)
    # Mutations (and adaptive followups) were generated by the LLM path.
    assert any(a.get("attack_source") == "llm" for a in result.attempts)


# --------------------------------------------------------------------------- #
#  LLM Judge refinement through a campaign (decision_path=llm + cost recorded)
# --------------------------------------------------------------------------- #
class _AmbiguousTarget:
    """Answers with no leak/defense marker, so the deterministic Judge returns
    'uncertain' and the LLM Judge is actually invoked to refine it."""

    def start_chat(self, pid):
        return "s"

    def _r(self):
        return TurnResult(content="Here is some general information.",
                          http_status=200, latency_ms=5.0)

    def chat_turn(self, session_id, message):
        return self._r()

    def agent_ask(self, pid, question):
        return self._r()


def test_campaign_uses_llm_judge_and_records_cost(tmp_path):
    store = ObservabilityStore(tmp_path / "run.jsonl")
    judge = JudgeAgent(llm=LlmJudge(_client()), model_name="fake-judge")
    result = run_campaign(
        target=_AmbiguousTarget(), seeds=_all_seeds(), store=store, judge=judge,
        max_rounds=1, max_attempts_per_round=2, enable_adaptive=False)
    assert any(v.get("decision_path") == "llm" for v in result.verdicts)
    # The LLM Judge path records its cost as an event.
    assert any(e.get("type") == "cost" and e.get("component") == "judge_llm"
               for e in store.events())
